joayong202503/joayong_front

package-lock.json, package.json, src/App.jsx, src/components/common/Button.jsx, src/components/common/Button.module.scss, src/components/common/DropDownSelect.jsx, src/components/common/DropDownSelect.module.scss, src/pages/TestPage.jsx, src/pages/TestPage.module.scss, src/styles/global.module.scss
- 버튼 공통 컴포넌트 생성
- 버튼 컴포넌트 생성
- props는 아래와 같음 
- 기타 컴포넌트 작성
- 임시로 인덱스 페이지에 클래스 이름 별 style 보이도록 해 두었음
=> [feature/common-UI] Create Button Component (버튼 컴포넌트 완성)

src/routes/AppRoutes.jsx
- router의 레이아웃 수정
- authLayout과 mainLayout 두가지로 레이아웃을 설정
- 각 페이지 이름 주석으로 추가
- mainLayout 설정
=> [Hotfix/layout change] fix router

package-lock.json, package.json, src/components/common/Card.module.scss, src/pages/MainPage.jsx, src/pages/MainPage.module.scss, src/services/exchangeApi.js
- 메인페이지 생성
- api 추가한 mainPage 생성
- 백엔드에서 내가 줄 재능, 내가 받을 재능, 프로필사진, 희망지역 받아와야 함
- css 더 보완해야함
=> [Feature/mainPage]메인페이지 생성

src/layouts/Header.module.scss
- header css 수정
- header에서 각 메뉴 호버, 클릭시 css 변경
- 추후에 header에도 api 적용
=> [hotfix/header]fix header css

src/components/common/Card.module.scss, src/pages/ExchangeListPage.jsx, src/pages/ExchangeListPage.module.scss
-재능교환 전체목록 페이지 1차완성
- card scss 일부 변경
- 전체 목록 페이지 생성
- 검색api 완성되면 검색 api 적용
=> [Feature/ExchangeListPage] 재능교환 전체페이지 1차완성

src/pages/MainPage.jsx, src/pages/MainPage.module.scss
- 메인페이지 수정
- 메인페이지 최근재능교환 슬라이드 수정
- 메인페이지 일부 css 수정
- 로그인 후에 프로필 클릭시 자신의 프로필 페이지로 이동되는 route 설정
- 프로필 페이지(내 프로필, 상대방 프로필 관리 )
=> [Feature/mainPage] 메인페이지 수정

src/pages/ExchangeListPage.jsx, src/services/exchangeApi.js
- ExchangeListPage 버그 수정
- 지역api를 제대로 가져오지 못한 부분 수정
- 페이지별로 재능교환게시물 가져오지 못한 부분 버그수정
- ExchangeListPage의 검색기능 추가
=> [Hotfix/ExchangeListPage] fix bugs

src/pages/ExchangeListPage.jsx, src/pages/ExchangeListPage.module.scss, src/routes/AppRoutes.jsx, src/services/exchangeApi.js, src/services/searchApi.js
- 검색 api 적용
- 카드 클릭시, 게시물 세부페이지로 넘어가지 않는 현상 수정
- 검색 api 적용
- 프로필페이지 완성
=> [Hotfix/exchangeListPage] Add search API

src/components/common/Card.module.scss, src/pages/MainPage.module.scss
- 디벨롭 병합 후 css 변경사항에 대해서 수정
-메인페이지의  card가 다 안보이는 현상에 대해서 수정
- 프로필페이지 진행
=> [Hotfix/mainpage] fix mainPage css

src/components/common/AlertModal.jsx, src/components/common/AlertModal.module.scss, src/components/common/Button.module.scss, src/components/common/ConfirmModal.jsx, src/components/common/ConfirmModal.module.scss, src/components/common/DropDownSelect.jsx, src/components/common/DropDownSelect.module.scss, src/components/common/MiniAlert.jsx, src/components/common/MiniAlert.module.scss, src/components/common/imagesAndFiles/ImageCarouselWithThumbNail.module.scss, src/components/common/imagesAndFiles/ImageUploadSection.jsx, src/components/common/imagesAndFiles/ImageUploadSection.module.scss, src/layouts/Header.module.scss, src/pages/ExchangeDetailPage.jsx, src/pages/ExchangeRequestPage.jsx, src/styles/global.module.scss
원인 불명의 Develop 브랜치 UI 망가짐 현상 발생 관련하여,  UI 원래와 최대한 비슷하게 복구했습니다.
1. ConfirmModal
- 원래대로 버튼 2개 가로로 배치되도록 수정
- 두 버튼에 모두 border 1px로 설정하여, 1px 미세한 높이 차이 수정
2. 상세 페이지
- 상세 페이지 진입 시 스크롤이 최하단에 내려가 있는 상태에서 시작되는 버그 수정
- 이미지 캐러셀에 상하 여백 줌
- radix ui 의 옵션 박스 드롭다운 오픈 시 스크롤 바 사라지는 강제 기능으로 인하여 화면 미세하게 왼쪽으로 밀리는 점 픽스
- 매칭 관리 페이지 작성
=> [hotfix/common-ui] Fix UI bug issues occured in Develop branchHotfix/design

package-lock.json, package.json, src/components/MatchesPage/MatchingMessageThumbnail.jsx, src/components/common/Footer.jsx, src/components/common/Footer.module.scss, src/layouts/Header.jsx, src/layouts/Header.module.scss, src/layouts/mainLayout.jsx
Header에 pending 매칭 요청 페이지 알람 설정 및 푸터 생성
- header : 본인이 수신인이고 수락/거절 하지 않은 pending 매칭 메시지가 있으면, header 매칭관리 메뉴에 알람 뜨게 구현
- footer : 아래 참고. 자유롭게 수정 해주세요.
-
=> [feature/header] show notifications when there's pending received message

src/components/ProfilePage/ProfileExchanges.module.scss, src/components/ProfilePage/ProfileRating.module.scss, src/components/common/Card.jsx, src/components/common/Card.module.scss, src/components/common/ProfileCircle.jsx, src/components/common/RatingBox.jsx, src/components/common/RatingBox.module.scss, src/layouts/Header.jsx, src/pages/ExchangeListPage.jsx, src/pages/MainPage.jsx, src/pages/ProfilePage.jsx, src/pages/ProfilePage.module.scss
- uiux 수정
- develop으로 병합시 바뀐 css 부분 수정
- 프로필 사진 클릭 시에 프로필페이지로 이동하도록 수정
- 리뷰등록 사이트 만들기
- 프로필사진 클릭 시, 프로필 페이지로 잘 이동함
=> [Hotfix/uiux] fix uiux

src/pages/MatchingRatingPage.jsx, src/pages/MatchingRatingPage.module.scss, src/routes/AppRoutes.jsx, src/services/reviewApi.js
- 매칭 후 리뷰 페이지 생성
- 매칭 후 리뷰 페이지 생성
- 에러 시 모달, 리뷰 완료시 모달 띄우기
=> [Feature/matchratingpage] 리뷰 페이지 생성

src/components/ProfilePage/ProfileExchanges.jsx, src/components/ProfilePage/ProfileExchanges.module.scss, src/components/ProfilePage/ProfileRating.module.scss, src/components/common/Card.module.scss, src/components/common/RatingBox.jsx, src/components/common/RatingBox.module.scss, src/pages/ExchangeListPage.jsx, src/pages/ExchangeListPage.module.scss, src/pages/MainPage.jsx, src/pages/MainPage.module.scss, src/pages/ProfilePage.jsx, src/pages/ProfilePage.module.scss, src/services/searchApi.js
- 전체적인 ui 수정
- 전체적인 css 수정
- 잘못된 검색어 입력 시, 버그 수정
- 메인페이지 소개섹션 추가
- 프로필 수정 페이지 완성
=> [Hotfix/ui-fixes] fix overall css

package-lock.json, package.json, src/components/ChatPage/RtcRoom.jsx, src/components/ChatPage/RtcRoom.module.scss, src/components/ChatPage/ToggleAudioButton.jsx, src/components/ChatPage/ToggleVideoButton.jsx, src/components/ChatPage/VideoView.jsx, src/pages/ChatPage.jsx, src/pages/ChatPage.module.scss, src/routes/AppRoutes.jsx, src/services/rtcApi.js, src/utils/janus.js
채팅방 기본 페이지 및 레이아웃 추가
RTC 모듈 추가
=> [feature/rtc] added basic RTC page and modules

src/components/ExchangeCreatePage/ContentInputSecition.jsx, src/components/ExchangeCreatePage/TitleInputSection.module.scss, src/components/common/DropDownBasic.jsx, src/components/common/DropDownBasic.module.scss, src/components/common/MiniAlert.jsx, src/components/common/categories/RegionSelectSection.jsx, src/hooks/exchangeEditPageHooks/useAutoFocus.js, src/hooks/exchangeEditPageHooks/useCategoryState.js, src/hooks/exchangeEditPageHooks/usePostData.js, src/hooks/exchangeEditPageHooks/useValidation.js, src/hooks/exchangesCreatePageHook/regionHooks.js, src/pages/ExchangeEditPage.jsx, src/pages/ExchangeEditPage.module.scss, src/pages/ExchangeRequestPage.jsx, src/pages/MatchesPage.jsx, src/services/api.js, src/services/postService.js, src/utils/sortAndGetCategories.js
- 재능 교환 게시글 수정
- 재능 교환 게시글 수정 페이지에서 기존 게시글 정보 불러오고, 변화 된 값을 상태관리
- 게시글 수정 후 fetch 하는 부분에 이미지 수정 추가 필요
- fetch 후 게시글 상세보기 페이지 캐시데이터 무효화
- 이미지 수정 추가
=> [feature/postEdit] Modify post data

src/components/ChatPage/RtcRoom.jsx, src/components/ChatPage/RtcRoom.module.scss, src/pages/ChatPage.module.scss
RTC 채팅방 css 변경
비디오 보더 색상 변경 
비디오/ 오디오 뮤트 아이콘 배치 변경
=> [style] update RTC chat icon position and line color

src/components/MatchesPage/RequestDetailModal.jsx, src/components/MatchesPage/RequestDetailModal.module.scss, src/pages/ExchangeCreatePage.module.scss, src/styles/global.module.scss
1.  MainLayout에서 margin-bottom 80px 제거
2. RequestDetailModal 페이지의 h2에 대하여, .postLink 클래스가 붙은 h2에만 적용되도록 수정
1. 상동
- X
=> [hotfix/css] delete margin botom of the MainLayout

src/components/ProfilePage/ProfileExchanges.module.scss, src/components/ProfilePage/ProfileRating.module.scss, src/components/common/ProfileCircle.module.scss, src/components/common/RatingBox.jsx, src/components/common/RatingBox.module.scss, src/pages/ProfilePage.module.scss
-ratingBox css 수정
- 프로필 페이지 내의 rating 디자인 수정
- 각기 다른 이미지 경로 하나로 통합하기
=> [hotfix/develop] fix style RatingBox

src/pages/LoginPage.jsx, src/pages/LoginPage.module.scss, src/pages/MatchesPage.jsx, src/store/slices/authSlice.js, src/utils/getCompleteImagePath.js
- 매칭 요청 메시지 발신인의 프로필 사진이 있을 시, 사진 제대로 화면에 표시되도록 버그 픽스
- 상동
- 기타 페이지 UX 개선
=> [Hotfix/matches] show message sender's profile image

src/components/ExchangeCreatePage/ContentInputSecition.jsx, src/components/MatchesPage/MatchingMessageThumbnail.jsx, src/components/common/imagesAndFiles/AdvancedImageUpload.jsx, src/components/common/imagesAndFiles/AdvancedImageUpload.module.scss, src/components/common/imagesAndFiles/ImageCarouselWithThumbNail.jsx, src/components/common/imagesAndFiles/ImageCarouselWithThumbNail.module.scss, src/hooks/ExchangeDetailPage/usePostData.js, src/hooks/exchangeEditPageHooks/useImageHandling.js, src/hooks/exchangeEditPageHooks/usePostModification.js, src/pages/ExchangeDetailPage.jsx, src/pages/ExchangeDetailPage.module.scss, src/pages/ExchangeEditPage.jsx, src/pages/ExchangeEditPage.module.scss, src/pages/ExchangeRequestPage.jsx, src/pages/LoginPage.jsx, src/pages/LoginPage.module.scss, src/pages/MatchesPage.jsx, src/pages/SearchTestPage.jsx, src/pages/SearchTestPage.module.scss, src/routes/AppRoutes.jsx, src/store/slices/authSlice.js, src/utils/getCompleteImagePath.js
- 아래 리팩토링 및 UX 개선, 기능 추가
1. 게시글 상세보기 페이지 : 연관 게시글 보기 추가 (로직 : 12개 게시글 검색하여, 그 중 랜덤으로 3개 보여줌)
2. 매칭 페이지 : 매칭 요청 메시지 발송 후 게시글 상세 페이지로 이동하도록 개선, textarea에서 엔터 키 작동하도록 픽스
3. 게시글 수정 페이지 : 페이지 진입 시 스크롤 중간 지점부터 보이는 점 픽스, 이미지 업로드 사진 확대보기 시 선택한 이미지가 제일 먼저 보이도록 개선
- 테스트, UX 개선, 잔버그 픽스
=> [refactor/variousPages] improve UX and add some functions of various pages

src/layouts/Header.jsx, src/layouts/Header.module.scss, src/pages/MainPage.jsx, src/pages/MainPage.module.scss
- 메인페이지 디자인 전체적으로 수정
- 헤더 수정(메인페이지에서만 투명하게 보이도록 수정)
- 메인페이지 수정(풀스크린백그라운드,애니메이션 일부 추가)
- 카드 컴포넌트 넓이 높이 수정할 수 있도록 수정
=> [Hotfix/style/mainPage] Redesign main page layout and visuals

src/layouts/Header.jsx, src/layouts/Header.module.scss
- 헤더 디자인 변경
- 배경색이 없어서 글씨가 겹쳐보이는 현상이 발생해서 스크롤 내릴때 배경색을 추가
- 회원가입 ui 변경
=> [feature/style/header] Add header transparency effect on scroll

.github/workflows/deploy.yml
=> deply.yml for CI/CD added

src/components/ChatPage/RtcRoom.jsx, src/components/ChatPage/RtcRoom.module.scss, src/components/chat/ChatRoom.jsx, src/components/chat/ChatRoom.module.scss, src/components/chat/websocket.js, src/pages/ChatPage.jsx, src/pages/ChatPage.module.scss, src/services/rtcApi.js
- 게시글 이동 링크 css 수정
- 상대방 이름 안뜨던 버그수정
- 채팅방 입장 시 인삿말 추가
=> Update chat room styling and fix bugs 

index.html, src/services/api.js, src/utils/getCompleteImagePath.js
1.  배포 후 백엔드 URL 설정
2.  배포 후 백엔드의 이미지 응답 주소(기존: /uploads/.... -> 변경 : 전체 주소) 변경에 따라, 프론트엔드 이에 맞게 수정
3.  파비콘 옆 문구 수정
상동
- 상세보기 페이지 지역 : 중분류까지 나오도록 수정(현재는 소분류만 나옴)
=> [hotfix/api] Update backend URL after deployment to production.

.github/workflows/deploy.yml
- 배포 기준 branch를 메인에서 develop로 변경
- 상동
=> [setting/deploy] change default deploy branch from main to develop

src/components/chat/ChatRoom.jsx
- 채팅방에서 상대 프로필과 이름이 잘못 뜨는 버그 수정
=> [hotfix/chat] fix bug where chatroom 

index.html, src/components/ProfilePage/ProfileExchanges.module.scss, src/components/common/Card.module.scss, src/pages/MainPage.module.scss
- 카드 디자인 수정 및 탭 제목 수정 
- 제목이 두줄 이상일 때, 카드를 벗어나는 현상 수정
- 리뷰 작성 오류 수정
=> [Hotfix/style/card] card css fix

src/components/chat/ChatRoom.jsx
- 채팅방에서 image src 주소 변경(백엔드 배포 후 image url 구조 변경에 맞추어)
=> [hotfix/chatroom] fix bug where profile image src is not properly set.

src/services/api.js
double check backend path after deployment to release
상동
-
=> [hotfix/api] double check backend path after deployment to release

src/services/api.js
- 백엔드 url 배포 후 변경에 따라, 프론트 코드도 변경
- 상동
=> [hotfix/api] dobule check backend path after deployment to release again

src/components/MatchesPage/MatchingMessageThumbnail.jsx, src/components/MatchesPage/RequestDetailModal.jsx, src/pages/MatchesPage.jsx, src/services/api.js, src/services/matchingService.js
- review statu 상세화(상대방만 리뷰 완료, 유저만 리뷰 완료, 모두 리뷰 미완료)에 따라 리뷰 완료 버튼 보이는 로직 변경
=> [feature/matches] divide review status in a more detailed way

src/components/MatchesPage/RequestDetailModal.module.scss
- 매칭관리 페이지의 메시지 확인 모달에서도 완료됨 버튼 css 적용
=> [feature/matches] improv css of completed button

src/components/ProfilePage/ProfileExchanges.jsx
- 프로필 페이지에서 내 게시물 페이지 변경 시 로딩스피너 추가
- 프로필 페이지에서 내 게시물 페이지 변경 시 로딩스피너 추가
- 배포 시 문제 발생 해결
=> [fix/profilePage] Add loading spinner for page transitions in ProfileExchanges

src/components/ProfilePage/ProfileExchanges.jsx, src/pages/ExchangeListPage.jsx, src/pages/MainPage.jsx
- 이미지 루트 변경
- 이미지 루트 변경
- 배포 후에도 이미지 잘 가져오는지 확인
=> [hotfix/YJ/imageRoute] fix imageRoute

src/components/ProfilePage/ProfileExchanges.jsx
- 이미지 루트 수정
- 배포 후 이미지 루트 수정
- 이미지 제대로 출력되는지 확인
=> [hotfix/imageRoute/YJ] fix imageRoute

src/styles/global.module.scss
- 배포 후 마진 생기는 현상 수정
- 배포 후 마진 생기는 현상 수정
- 배포후 스타일 확인
-
=> [fix/style/globalscss] fix global.scss

src/App.jsx
- app.jsx의 globalscss import 부분 수정
- app.jsx의 globalscss import 부분 수정
=> [fix/style/globalscss] Modifying import declarations in App.jsx

src/styles/global.scss
- 배포후 마진생기는 현상 수정중
- 배포후 마진생기는 현상 수정중
=> [fix/globalscss] Fix margin issue after deployment

src/styles/global.scss
- 폰트 스타일 수정
- 폰트 스타일 수정
-ppt 수정, 리드미 작성
=> [fix/addFont] fix fontStyle

src/components/chat/ChatRoom.jsx, src/components/chat/websocket.js, src/components/common/AlertModal.jsx, src/components/common/ProfileCircle.jsx, src/components/common/ReduxFetcher.jsx, src/components/common/categories/RegionSelectSection.jsx, src/pages/ChatPage.jsx, src/pages/ExchangeCreatePage.jsx, src/pages/ExchangeEditPage.jsx, src/pages/ExchangeListPage.jsx, src/pages/MatchesPage.jsx, src/pages/MatchingRatingPage.jsx, src/pages/ProfileSettingPage.jsx, src/pages/SignUp.jsx, src/pages/testPages/TestPage.jsx, src/services/matchingService.js, src/services/profileApi.js
- 배포 후 로그 지우기 
- 배포 후 로그 지우기
-ppt 페이지 기능 설명 수정
=> [feature/log-cleanup] remove console.log statements for production except webrtc and error message

src/services/postService.js
PostService.JS의 deletePost 함수의 에러 핸들링 부분 리팩토링
network error 발생할 경우, error를 catch한 후 커스텀 ApiError 클래스에서 status를 503으로 설정
없음
=> [Refactor/deletePost] Refactor post delete error handling code
